# Generated by Django 4.1.7 on 2023-06-06 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Social", "0005_user_rename_post_post_blog_alter_like_user_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post_blog",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
